# Generated by Django 3.0.6 on 2020-06-15 21:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=30)),
                ('country_number', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='dealer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='id',
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_email',
            field=models.CharField(default='invalid', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_name',
            field=models.CharField(default='delear', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='null', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AddField(
            model_name='dealer',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dealers.City'),
            preserve_default=False,
        ),
    ]
