# Generated by Django 3.0.5 on 2020-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200503_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('price', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'Dish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=30)),
                ('employee_last_name', models.CharField(max_length=30)),
                ('employee_birthday', models.DateField()),
                ('employee_phone_number', models.CharField(max_length=13, unique=True)),
                ('employee_address', models.CharField(blank=True, max_length=50)),
                ('employee_salary', models.FloatField()),
                ('employee_work_experience', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_address', models.CharField(blank=True, max_length=60)),
                ('restaurant_number', models.CharField(blank=True, max_length=13, unique=True)),
            ],
            options={
                'db_table': 'Restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Restaurant_menu',
                'managed': False,
            },
        ),
    ]
